In [1]:
import sys, os
sys.path.append(os.getenv('DRSNDIR'))
from drsn.statistics.descriptive import *
pd.set_option('display.max_colwidth', 90)
pd.set_option('display.max_columns', None)
pd.set_option('display.min_rows', 200)
pd.set_option('display.max_rows', 220)
pd.set_option('display.width', 1000)
pd.set_option("display.precision", 3)
pd.options.display.float_format = "{:,.3f}".format

In [3]:
comp_df.dropna()[['orig_just4_median', 'new_just4_median']].groupby(['subjects'], axis=0).describe(percentiles=[.25, .5, .75], include='all')

         orig_just4_median                            new_just4_median         \
                     count unique            top freq            count unique
subjects
50002                195.0  195.0  107519.820312  1.0            195.0  195.0
50007                195.0  195.0   61468.695312  1.0            195.0  195.0
50012                195.0  195.0   75519.765625  1.0            195.0  195.0
50017                195.0  195.0   78588.085938  1.0            195.0  195.0
50024                195.0  195.0   69887.921875  1.0            195.0  195.0
...                    ...    ...            ...  ...              ...    ...
51567                195.0  195.0     112.725899  1.0            195.0  195.0
51572                195.0  195.0     196.968338  1.0            195.0  195.0
51577                195.0  195.0     549.706604  1.0            195.0  195.0
51582                195.0  195.0     428.703430  1.0            195.0  195.0
51607                115.0  115.0  150014.781250  1.0            115.0  115.0


                    top freq
subjects
50002      86015.093750  1.0
50007      56319.054688  1.0
50012      67668.218750  1.0
50017      62719.750000  1.0
50024      61439.703125  1.0
...                 ...  ...
51567         24.491617  1.0
51572         41.281639  1.0
51577        204.434036  1.0
51582        142.707718  1.0
51607     134394.140625  1.0

[183 rows x 8 columns]

In [5]:
pd.get_option("display.max_rows")

10